//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM-Beziehungsmetadaten

[assembly: EdmRelationshipAttribute("db_MERPModel", "FK__tbl_Prd__PrdPrdC__0519C6AF", "tbl_Prdcat", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Database.tbl_Prdcat), "tbl_Prd", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Database.tbl_Prd), true)]

#endregion

namespace Database
{
    #region Kontexte
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    public partial class db_MERPEntities1 : ObjectContext
    {
        #region Konstruktoren
    
        /// <summary>
        /// Initialisiert ein neues db_MERPEntities1-Objekt mithilfe der in Abschnitt 'db_MERPEntities1' der Anwendungskonfigurationsdatei gefundenen Verbindungszeichenfolge.
        /// </summary>
        public db_MERPEntities1() : base("name=db_MERPEntities1", "db_MERPEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisiert ein neues db_MERPEntities1-Objekt.
        /// </summary>
        public db_MERPEntities1(string connectionString) : base(connectionString, "db_MERPEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisiert ein neues db_MERPEntities1-Objekt.
        /// </summary>
        public db_MERPEntities1(EntityConnection connection) : base(connection, "db_MERPEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partielle Methoden
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet-Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<tbl_Prd> tbl_Prd
        {
            get
            {
                if ((_tbl_Prd == null))
                {
                    _tbl_Prd = base.CreateObjectSet<tbl_Prd>("tbl_Prd");
                }
                return _tbl_Prd;
            }
        }
        private ObjectSet<tbl_Prd> _tbl_Prd;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<tbl_Prdcat> tbl_Prdcat
        {
            get
            {
                if ((_tbl_Prdcat == null))
                {
                    _tbl_Prdcat = base.CreateObjectSet<tbl_Prdcat>("tbl_Prdcat");
                }
                return _tbl_Prdcat;
            }
        }
        private ObjectSet<tbl_Prdcat> _tbl_Prdcat;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<tbl_Usr> tbl_Usr
        {
            get
            {
                if ((_tbl_Usr == null))
                {
                    _tbl_Usr = base.CreateObjectSet<tbl_Usr>("tbl_Usr");
                }
                return _tbl_Usr;
            }
        }
        private ObjectSet<tbl_Usr> _tbl_Usr;

        #endregion
        #region AddTo-Methoden
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'tbl_Prd'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddTotbl_Prd(tbl_Prd tbl_Prd)
        {
            base.AddObject("tbl_Prd", tbl_Prd);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'tbl_Prdcat'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddTotbl_Prdcat(tbl_Prdcat tbl_Prdcat)
        {
            base.AddObject("tbl_Prdcat", tbl_Prdcat);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'tbl_Usr'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddTotbl_Usr(tbl_Usr tbl_Usr)
        {
            base.AddObject("tbl_Usr", tbl_Usr);
        }

        #endregion
    }
    

    #endregion
    
    #region Entitäten
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_MERPModel", Name="tbl_Prd")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Prd : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues tbl_Prd-Objekt.
        /// </summary>
        /// <param name="prd_">Anfangswert der Eigenschaft Prd_.</param>
        public static tbl_Prd Createtbl_Prd(global::System.Int32 prd_)
        {
            tbl_Prd tbl_Prd = new tbl_Prd();
            tbl_Prd.Prd_ = prd_;
            return tbl_Prd;
        }

        #endregion
        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Prd_
        {
            get
            {
                return _Prd_;
            }
            set
            {
                if (_Prd_ != value)
                {
                    OnPrd_Changing(value);
                    ReportPropertyChanging("Prd_");
                    _Prd_ = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Prd_");
                    OnPrd_Changed();
                }
            }
        }
        private global::System.Int32 _Prd_;
        partial void OnPrd_Changing(global::System.Int32 value);
        partial void OnPrd_Changed();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrdName
        {
            get
            {
                return _PrdName;
            }
            set
            {
                OnPrdNameChanging(value);
                ReportPropertyChanging("PrdName");
                _PrdName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrdName");
                OnPrdNameChanged();
            }
        }
        private global::System.String _PrdName;
        partial void OnPrdNameChanging(global::System.String value);
        partial void OnPrdNameChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrdEAN
        {
            get
            {
                return _PrdEAN;
            }
            set
            {
                OnPrdEANChanging(value);
                ReportPropertyChanging("PrdEAN");
                _PrdEAN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrdEAN");
                OnPrdEANChanged();
            }
        }
        private global::System.String _PrdEAN;
        partial void OnPrdEANChanging(global::System.String value);
        partial void OnPrdEANChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PrdPricePurchase
        {
            get
            {
                return _PrdPricePurchase;
            }
            set
            {
                OnPrdPricePurchaseChanging(value);
                ReportPropertyChanging("PrdPricePurchase");
                _PrdPricePurchase = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrdPricePurchase");
                OnPrdPricePurchaseChanged();
            }
        }
        private Nullable<global::System.Double> _PrdPricePurchase;
        partial void OnPrdPricePurchaseChanging(Nullable<global::System.Double> value);
        partial void OnPrdPricePurchaseChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PrdPriceSale
        {
            get
            {
                return _PrdPriceSale;
            }
            set
            {
                OnPrdPriceSaleChanging(value);
                ReportPropertyChanging("PrdPriceSale");
                _PrdPriceSale = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrdPriceSale");
                OnPrdPriceSaleChanged();
            }
        }
        private Nullable<global::System.Double> _PrdPriceSale;
        partial void OnPrdPriceSaleChanging(Nullable<global::System.Double> value);
        partial void OnPrdPriceSaleChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PrdPrdcat_
        {
            get
            {
                return _PrdPrdcat_;
            }
            set
            {
                OnPrdPrdcat_Changing(value);
                ReportPropertyChanging("PrdPrdcat_");
                _PrdPrdcat_ = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrdPrdcat_");
                OnPrdPrdcat_Changed();
            }
        }
        private Nullable<global::System.Int32> _PrdPrdcat_;
        partial void OnPrdPrdcat_Changing(Nullable<global::System.Int32> value);
        partial void OnPrdPrdcat_Changed();

        #endregion
    
        #region Navigationseigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_MERPModel", "FK__tbl_Prd__PrdPrdC__0519C6AF", "tbl_Prdcat")]
        public tbl_Prdcat tbl_Prdcat
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Prdcat>("db_MERPModel.FK__tbl_Prd__PrdPrdC__0519C6AF", "tbl_Prdcat").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Prdcat>("db_MERPModel.FK__tbl_Prd__PrdPrdC__0519C6AF", "tbl_Prdcat").Value = value;
            }
        }
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_Prdcat> tbl_PrdcatReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Prdcat>("db_MERPModel.FK__tbl_Prd__PrdPrdC__0519C6AF", "tbl_Prdcat");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_Prdcat>("db_MERPModel.FK__tbl_Prd__PrdPrdC__0519C6AF", "tbl_Prdcat", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_MERPModel", Name="tbl_Prdcat")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Prdcat : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues tbl_Prdcat-Objekt.
        /// </summary>
        /// <param name="prdcat_">Anfangswert der Eigenschaft Prdcat_.</param>
        public static tbl_Prdcat Createtbl_Prdcat(global::System.Int32 prdcat_)
        {
            tbl_Prdcat tbl_Prdcat = new tbl_Prdcat();
            tbl_Prdcat.Prdcat_ = prdcat_;
            return tbl_Prdcat;
        }

        #endregion
        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Prdcat_
        {
            get
            {
                return _Prdcat_;
            }
            set
            {
                if (_Prdcat_ != value)
                {
                    OnPrdcat_Changing(value);
                    ReportPropertyChanging("Prdcat_");
                    _Prdcat_ = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Prdcat_");
                    OnPrdcat_Changed();
                }
            }
        }
        private global::System.Int32 _Prdcat_;
        partial void OnPrdcat_Changing(global::System.Int32 value);
        partial void OnPrdcat_Changed();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrdcatName
        {
            get
            {
                return _PrdcatName;
            }
            set
            {
                OnPrdcatNameChanging(value);
                ReportPropertyChanging("PrdcatName");
                _PrdcatName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrdcatName");
                OnPrdcatNameChanged();
            }
        }
        private global::System.String _PrdcatName;
        partial void OnPrdcatNameChanging(global::System.String value);
        partial void OnPrdcatNameChanged();

        #endregion
    
        #region Navigationseigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_MERPModel", "FK__tbl_Prd__PrdPrdC__0519C6AF", "tbl_Prd")]
        public EntityCollection<tbl_Prd> tbl_Prd
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_Prd>("db_MERPModel.FK__tbl_Prd__PrdPrdC__0519C6AF", "tbl_Prd");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_Prd>("db_MERPModel.FK__tbl_Prd__PrdPrdC__0519C6AF", "tbl_Prd", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_MERPModel", Name="tbl_Usr")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Usr : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues tbl_Usr-Objekt.
        /// </summary>
        /// <param name="usr_">Anfangswert der Eigenschaft usr_.</param>
        /// <param name="usrIdent">Anfangswert der Eigenschaft usrIdent.</param>
        /// <param name="usrName">Anfangswert der Eigenschaft usrName.</param>
        /// <param name="usrPassword">Anfangswert der Eigenschaft usrPassword.</param>
        /// <param name="usrLogedin">Anfangswert der Eigenschaft usrLogedin.</param>
        public static tbl_Usr Createtbl_Usr(global::System.Int32 usr_, global::System.String usrIdent, global::System.String usrName, global::System.String usrPassword, global::System.Boolean usrLogedin)
        {
            tbl_Usr tbl_Usr = new tbl_Usr();
            tbl_Usr.usr_ = usr_;
            tbl_Usr.usrIdent = usrIdent;
            tbl_Usr.usrName = usrName;
            tbl_Usr.usrPassword = usrPassword;
            tbl_Usr.usrLogedin = usrLogedin;
            return tbl_Usr;
        }

        #endregion
        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 usr_
        {
            get
            {
                return _usr_;
            }
            set
            {
                if (_usr_ != value)
                {
                    Onusr_Changing(value);
                    ReportPropertyChanging("usr_");
                    _usr_ = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("usr_");
                    Onusr_Changed();
                }
            }
        }
        private global::System.Int32 _usr_;
        partial void Onusr_Changing(global::System.Int32 value);
        partial void Onusr_Changed();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String usrIdent
        {
            get
            {
                return _usrIdent;
            }
            set
            {
                OnusrIdentChanging(value);
                ReportPropertyChanging("usrIdent");
                _usrIdent = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("usrIdent");
                OnusrIdentChanged();
            }
        }
        private global::System.String _usrIdent;
        partial void OnusrIdentChanging(global::System.String value);
        partial void OnusrIdentChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String usrName
        {
            get
            {
                return _usrName;
            }
            set
            {
                OnusrNameChanging(value);
                ReportPropertyChanging("usrName");
                _usrName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("usrName");
                OnusrNameChanged();
            }
        }
        private global::System.String _usrName;
        partial void OnusrNameChanging(global::System.String value);
        partial void OnusrNameChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String usrPassword
        {
            get
            {
                return _usrPassword;
            }
            set
            {
                OnusrPasswordChanging(value);
                ReportPropertyChanging("usrPassword");
                _usrPassword = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("usrPassword");
                OnusrPasswordChanged();
            }
        }
        private global::System.String _usrPassword;
        partial void OnusrPasswordChanging(global::System.String value);
        partial void OnusrPasswordChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean usrLogedin
        {
            get
            {
                return _usrLogedin;
            }
            set
            {
                OnusrLogedinChanging(value);
                ReportPropertyChanging("usrLogedin");
                _usrLogedin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("usrLogedin");
                OnusrLogedinChanged();
            }
        }
        private global::System.Boolean _usrLogedin;
        partial void OnusrLogedinChanging(global::System.Boolean value);
        partial void OnusrLogedinChanged();

        #endregion
    
    }

    #endregion
    
}
